version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  clean-build:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    steps:
      - checkout
      - run:
          name: clean install
          command: mvn clean install -DskipTests

  test:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    steps:
      - checkout
      - run:
          name: test code
          command: mvn test

  build-and-push-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_USERNAME/capstone-cloud-devops-${CIRCLE_WORKFLOW_ID:0:7}
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_USERNAME/capstone-cloud-devops-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  default:
    jobs:
      - clean-build
      - test:
          requires: [clean-build]
      - build-and-push-image:
          requires: [test]