apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-east-1
  version: "1.27"

availabilityZones: ["us-east-1a", "us-east-1b"]

nodeGroups:
  - name: capstone-ng-1
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
